<a href="https://colab.research.google.com/github/prajwal-ky22/Data-Science-Algorithms/blob/main/Knn_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/balaji2v/Inceptez_Batch19/main/teleCust1000t.csv")

In [5]:
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [6]:
df.shape

(1000, 12)

In [7]:
df.describe(include='all').T

count    mean         std   min   25%   50%   75%     max
region   1000.0   2.022    0.816200   1.0   1.0   2.0   3.0     3.0
tenure   1000.0  35.526   21.359812   1.0  17.0  34.0  54.0    72.0
age      1000.0  41.684   12.558816  18.0  32.0  40.0  51.0    77.0
marital  1000.0   0.495    0.500225   0.0   0.0   0.0   1.0     1.0
address  1000.0  11.551   10.086681   0.0   3.0   9.0  18.0    55.0
income   1000.0  77.535  107.044165   9.0  29.0  47.0  83.0  1668.0
ed       1000.0   2.671    1.222397   1.0   2.0   3.0   4.0     5.0
employ   1000.0  10.987   10.082087   0.0   3.0   8.0  17.0    47.0
retire   1000.0   0.047    0.211745   0.0   0.0   0.0   0.0     1.0
gender   1000.0   0.517    0.499961   0.0   0.0   1.0   1.0     1.0
reside   1000.0   2.331    1.435793   1.0   1.0   2.0   3.0     8.0
custcat  1000.0   2.487    1.120306   1.0   1.0   3.0   3.0     4.0

In [8]:
df['custcat'].nunique()

4

In [9]:
df['custcat'].value_counts()

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [10]:
x = df.iloc[:,:-1]

In [11]:
x.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  
0       2  
1       6  
2       2  
3       1  
4       4

In [12]:
y = df.iloc[:,-1]

In [13]:
y.head()

0    1
1    4
2    3
3    1
4    3
Name: custcat, dtype: int64

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=1)

In [15]:
x_train.head()

region  tenure  age  marital  address  income  ed  employ  retire  \
731       1       8   42        1        2   129.0   4      17     0.0   
716       1      65   70        1        9   115.0   2      39     1.0   
640       2      20   38        0       19   237.0   4      13     0.0   
804       3      33   30        1        5    22.0   1       0     0.0   
737       1      15   38        1       11    46.0   5      11     0.0   

     gender  reside  
731       1       3  
716       1       2  
640       0       1  
804       0       2  
737       0       3

In [16]:
x_train.size

7700

In [17]:
x_test.head()

region  tenure  age  marital  address  income  ed  employ  retire  \
507       2       2   28        0        7    46.0   3       0     0.0   
818       3       5   35        1        9    59.0   3       8     0.0   
452       2      10   56        0       26     9.0   2       6     1.0   
368       3      63   56        0       17    71.0   3      18     0.0   
242       3      61   76        0       39    15.0   1      29     1.0   

     gender  reside  
507       1       1  
818       1       5  
452       0       2  
368       1       1  
242       0       1

In [18]:
y_train.head()

731    1
716    4
640    4
804    3
737    1
Name: custcat, dtype: int64

In [19]:
y_test.head()

507    4
818    4
452    1
368    1
242    3
Name: custcat, dtype: int64

In [20]:
# This will be used to normalize the parameter values to the same scale
scaler = StandardScaler()

In [21]:
# This will calculate the mean and standard deviation to be used for the scaling
# Note that the scale is calculated only for the training data set, to be used
# to scale both the train and test data set. This is to avoid the mean and SD
# of all data (both train and test) to contaminate the train the data set used
# for the prediction later on
scaler.fit(x_train)

StandardScaler()

In [22]:
# This will normalize the training data using the mean and SD calculated above
# The resulting numpy array will have (x - mean) / SD for each columns
x_scl_train = scaler.transform(x_train)

In [23]:
x_scl_train

array([[-1.21518236, -1.29475923,  0.01808631, ..., -0.23958675,
         0.97182532,  0.48764622],
       [-1.21518236,  1.35710121,  2.21989742, ...,  4.17385345,
         0.97182532, -0.20615938],
       [ 0.0105059 , -0.73647282, -0.29645814, ..., -0.23958675,
        -1.02899151, -0.89996498],
       ...,
       [ 1.23619416, -1.43433083, -0.21782203, ..., -0.23958675,
         0.97182532, -0.20615938],
       [ 0.0105059 ,  0.7988148 ,  1.19762797, ..., -0.23958675,
        -1.02899151, -0.89996498],
       [-1.21518236,  0.3801    ,  1.19762797, ..., -0.23958675,
        -1.02899151, -0.20615938]])

In [24]:
x_scl_train.size

7700

In [25]:
# This will normalize the test data using the mean and SD calculated above
# The resulting numpy array will have (x - mean) / SD for each columns
x_scl_test = scaler.transform(x_test)

In [26]:
x_scl_test

array([[ 0.0105059 , -1.57390243, -1.08281925, ..., -0.23958675,
         0.97182532, -0.89996498],
       [ 1.23619416, -1.43433083, -0.53236647, ..., -0.23958675,
         0.97182532,  1.87525743],
       [ 0.0105059 , -1.2017115 ,  1.11899186, ...,  4.17385345,
        -1.02899151, -0.20615938],
       ...,
       [ 0.0105059 ,  0.93838641,  0.64717519, ..., -0.23958675,
         0.97182532,  1.18145183],
       [ 0.0105059 ,  0.47314773,  0.41126686, ..., -0.23958675,
         0.97182532, -0.20615938],
       [ 0.0105059 ,  0.28705226, -0.76827481, ..., -0.23958675,
         0.97182532,  2.56906303]])

In [27]:
x_scl_test.size

3300

In [28]:
y_train.value_counts()

3    201
1    176
4    165
2    158
Name: custcat, dtype: int64

In [29]:
y_test.value_counts()

1    90
3    80
4    71
2    59
Name: custcat, dtype: int64

In [30]:
# Prepare to predict using the KNN classifier method
knn = KNeighborsClassifier()

In [31]:
# Perform model fit based on the training data. This will apply the algorithm
# on the train data
knn.fit(x_scl_train, y_train)

KNeighborsClassifier()

In [32]:
# Now predict based on the training data
y_pred_train = knn.predict(x_scl_train)

In [33]:
y_pred_train

array([1, 2, 1, 3, 2, 1, 1, 2, 3, 2, 2, 3, 4, 2, 1, 3, 3, 2, 3, 1, 2, 1,
       1, 4, 1, 3, 4, 1, 3, 4, 1, 2, 3, 4, 2, 3, 2, 1, 3, 2, 3, 2, 2, 1,
       1, 1, 3, 2, 1, 1, 4, 3, 2, 3, 3, 4, 4, 2, 3, 2, 4, 1, 4, 2, 3, 3,
       3, 1, 3, 4, 2, 2, 1, 3, 2, 3, 4, 2, 1, 4, 1, 1, 4, 3, 2, 1, 2, 4,
       3, 1, 2, 1, 1, 4, 1, 2, 1, 1, 2, 3, 1, 3, 3, 3, 1, 1, 2, 3, 2, 3,
       2, 3, 2, 2, 2, 4, 1, 1, 3, 4, 2, 2, 1, 2, 4, 2, 2, 2, 1, 1, 2, 3,
       3, 2, 1, 1, 3, 2, 3, 1, 4, 1, 1, 1, 1, 1, 3, 1, 4, 4, 4, 3, 1, 2,
       2, 3, 3, 3, 2, 1, 3, 1, 1, 3, 4, 2, 3, 2, 1, 2, 2, 1, 2, 1, 1, 3,
       3, 4, 1, 2, 3, 1, 3, 2, 1, 4, 2, 3, 3, 1, 2, 3, 4, 2, 4, 3, 2, 2,
       4, 2, 2, 1, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 4, 1, 2, 1, 1, 1, 1, 2,
       1, 3, 1, 1, 3, 1, 1, 1, 1, 4, 2, 3, 2, 2, 3, 3, 1, 4, 4, 3, 3, 3,
       3, 2, 4, 1, 1, 3, 2, 1, 1, 2, 3, 4, 1, 4, 1, 3, 2, 2, 1, 2, 4, 3,
       4, 4, 2, 2, 2, 2, 1, 2, 1, 4, 1, 4, 1, 2, 4, 1, 4, 1, 2, 4, 1, 3,
       3, 2, 4, 4, 1, 2, 3, 3, 2, 3, 2, 1, 3, 2, 4,

In [34]:
y_pred_test = knn.predict(x_scl_test)

In [35]:
y_pred_test

array([1, 1, 1, 4, 1, 1, 2, 2, 3, 2, 4, 3, 2, 2, 1, 4, 3, 3, 4, 1, 3, 1,
       3, 1, 4, 3, 1, 3, 3, 1, 1, 3, 1, 2, 2, 3, 3, 1, 1, 3, 4, 2, 4, 3,
       2, 1, 3, 1, 3, 1, 2, 2, 1, 4, 4, 4, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 2, 3, 2, 3, 2, 3, 1, 1, 3, 1, 4, 2, 1, 3, 3, 2, 3, 3, 1, 3,
       3, 3, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 4, 3, 3, 1, 2, 2,
       3, 2, 1, 4, 1, 1, 3, 1, 3, 1, 2, 2, 4, 1, 2, 3, 4, 4, 2, 4, 4, 4,
       2, 2, 3, 3, 3, 1, 2, 3, 4, 3, 3, 2, 4, 1, 2, 3, 2, 3, 2, 3, 3, 2,
       3, 1, 4, 3, 4, 1, 3, 1, 1, 1, 4, 4, 3, 1, 1, 1, 4, 3, 1, 1, 1, 4,
       2, 1, 4, 1, 3, 2, 4, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 3, 1, 2,
       4, 1, 4, 1, 1, 4, 2, 4, 4, 4, 1, 2, 1, 2, 3, 2, 1, 1, 2, 4, 2, 2,
       2, 4, 3, 4, 1, 1, 3, 1, 3, 2, 3, 1, 1, 3, 3, 3, 2, 3, 1, 2, 4, 1,
       3, 2, 4, 2, 2, 1, 1, 2, 4, 3, 3, 4, 2, 3, 1, 3, 1, 2, 1, 3, 2, 3,
       1, 4, 1, 1, 1, 2, 2, 3, 4, 1, 1, 1, 4, 1, 1, 3, 2, 3, 2, 2, 3, 2,
       4, 4, 4, 4, 3, 4, 2, 2, 1, 1, 4, 1, 2, 2])

In [36]:
accuracy_score(y_pred_train, y_train)

0.5557142857142857

In [37]:
accuracy_score(y_pred_test, y_test)

0.33

In [38]:
precision_score(y_pred_test, y_test, average='weighted')

0.34286983988046293

In [39]:
precision_score(y_pred_test, y_test, average='weighted')

0.34286983988046293

In [40]:
confusion_matrix(y_pred_train, y_train)

array([[117,  31,  40,  35],
       [ 17,  87,  34,  37],
       [ 23,  25, 114,  22],
       [ 19,  15,  13,  71]])

In [41]:
confusion_matrix(y_pred_test, y_test)

array([[43, 11, 25, 27],
       [19, 14, 20, 17],
       [18, 14, 28, 13],
       [10, 20,  7, 14]])

In [42]:
print(classification_report(y_pred_train, y_train))

              precision    recall  f1-score   support

           1       0.66      0.52      0.59       223
           2       0.55      0.50      0.52       175
           3       0.57      0.62      0.59       184
           4       0.43      0.60      0.50       118

    accuracy                           0.56       700
   macro avg       0.55      0.56      0.55       700
weighted avg       0.57      0.56      0.56       700



In [43]:
print(classification_report(y_pred_test, y_test))

              precision    recall  f1-score   support

           1       0.48      0.41      0.44       106
           2       0.24      0.20      0.22        70
           3       0.35      0.38      0.37        73
           4       0.20      0.27      0.23        51

    accuracy                           0.33       300
   macro avg       0.32      0.32      0.31       300
weighted avg       0.34      0.33      0.33       300

